# @package _global_

# GenEval Beam Search with Janus + ImageReward Verifier

defaults:
  - /eval/base
  - /components/ar_priors/janus/janus
  - /components/search_algorithms/janus/beam_janus
  - /components/verifiers/image_reward

dataset:
  name: geneval
  dataset_dir: datasets/geneval
